name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: nx-augustinesmith/deployed-commit-action@v1
              with:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
                COMMITTER: ${{ github.event.commits[0].author.username }}