name: Test

on:
  push:
    branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - run: |
              npm install
          - uses: actions/setup-node@v3
            with:
              node-version-file: '.nvmrc'

          - name: Derive appropriate SHAs for base and head for `nx affected` commands
            uses: nrwl/nx-set-shas@v3

          - uses: nx-augustinesmith/deployed-commit-action@v1
            with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
              COMMITTER: ${{ github.event.commits[0].author.username }}
              BASE: ${{ env.NX_BASE }}
              HEAD: ${{ env.NX_HEAD }}